# Generated by Django 4.2.7 on 2024-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('given_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('given_by', models.TextField(max_length=20)),
                ('complete', models.BooleanField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
