# Generated by Django 4.2.7 on 2024-01-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='share_with',
            field=models.TextField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
