# Generated by Django 4.2.7 on 2024-02-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_execute_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='share_with',
        ),
    ]
