# Generated by Django 4.2.7 on 2024-02-03 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_task_finish_date_alter_task_given_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='given_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
